//commonReducer



//authRducer

export const LOCAL_LOGIN_REQUEST = 'LOCAL_LOGIN_REQUEST'
export const LOCAL_LOGIN_SUCCESS = 'LOCAL_LOGIN_SUCCESS';
export const LOCAL_LOGIN_ERROR = 'LOCAL_LOGIN_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGOUT = 'LOGOUT'

//hubReducer 
export const FETCH_HUBS = 'FETCH_HUBS'

export const FETCH_HUB_REQUEST = 'FETCH_HUB_REQUEST';
export const FETCH_HUB_SUCCESS = 'FETCH_HUB_SUCCESS';
export const FETCH_HUB_ERROR = 'FETCH_HUB_ERROR';

export const CREATE_HUB_REQUEST = 'CREATE_HUB_REQUEST'
export const CREATE_HUB_SUCCESS = 'CREATE_HUB_SUCCESS'
export const CREATE_HUB_ERROR = 'CREATE_HUB_ERROR'

export const SUBSCRIBE_REQUEST= 'SUBSCRIBE_REQUEST';
export const SUBSCRIBE_ERROR= 'SUBSCRIBE_ERROR';
export const SUBSCRIBE_SUCCESS= 'SUBSCRIBE_SUCCESS';

export const UNSUBSCRIBE_REQUEST= 'UNSUBSCRIBE_REQUEST';
export const UNSUBSCRIBE_ERROR= 'UNSUBSCRIBE_ERROR';
export const UNSUBSCRIBE_SUCCESS= 'UNSUBSCRIBE_SUCCESS';

//modalRducer

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL'

